### ISSUE TITLE
[Question / Windows] Installation instructions?

### ISSUE THREAD

**Issue by GATOQSECOMIO** [bimal-b/ContiGUI#1]
Is there any guide to install?

Sorry for my bad english

**Comment by Only-Bimal** [comment]
There is nothing to install. Just Compile the solution and run the executable. I haven't prepared any release yet.
Just one thing to remember that it is still a work in progress.  so somethings may not work. :)

**Comment by GATOQSECOMIO** [comment]
nice! thanks
close issue
